/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Validaciones;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Sebas
 */
public class ConfirmarReservaFrame extends javax.swing.JFrame {

    public int c = 0;
    public int Horas;
//    Icon Imagenes  = new ImageIcon(getClass().getResource("1hora.png"));
    Icon miIcono = new ImageIcon("1hora.png");

    /**
     * Creates new form ConfirmarReserva
     */
    public ConfirmarReservaFrame() {
        initComponents();
        pnlSelector.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblMinuto = new javax.swing.JTextField();
        lblHora = new javax.swing.JTextField();
        lblFecha = new javax.swing.JTextField();
        lblNombre = new javax.swing.JTextField();
        lblElegir = new javax.swing.JLabel();
        pnlSelector = new javax.swing.JPanel();
        optPrimeraHora = new javax.swing.JLabel();
        optSegundaHora = new javax.swing.JLabel();
        optTerceraH = new javax.swing.JLabel();
        optCuartaH = new javax.swing.JLabel();
        optQuintaH = new javax.swing.JLabel();
        optDoceH = new javax.swing.JLabel();
        optSextaH = new javax.swing.JLabel();
        optAllDay = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        lblElegido = new javax.swing.JLabel();
        labelHorasC = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnConfirmar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, 60, 60));

        jScrollPane1.setBackground(new java.awt.Color(13, 17, 23));

        jTable1.setBackground(new java.awt.Color(13, 17, 23));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 240, 181));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, 680, 600));

        lblMinuto.setBackground(new java.awt.Color(22, 27, 34));
        lblMinuto.setFont(new java.awt.Font("Roboto", 0, 26)); // NOI18N
        lblMinuto.setForeground(new java.awt.Color(204, 204, 204));
        lblMinuto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblMinuto.setText("00");
        lblMinuto.setBorder(null);
        lblMinuto.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblMinuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinutoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinutoMouseExited(evt);
            }
        });
        lblMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMinutoActionPerformed(evt);
            }
        });
        jPanel1.add(lblMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 80, 30));

        lblHora.setBackground(new java.awt.Color(22, 27, 34));
        lblHora.setFont(new java.awt.Font("Roboto", 0, 26)); // NOI18N
        lblHora.setForeground(new java.awt.Color(204, 204, 204));
        lblHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblHora.setText("00");
        lblHora.setBorder(null);
        lblHora.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHoraMouseExited(evt);
            }
        });
        lblHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHoraActionPerformed(evt);
            }
        });
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 80, 30));

        lblFecha.setBackground(new java.awt.Color(22, 27, 34));
        lblFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 204, 204));
        lblFecha.setText("DD/MM/AAAA");
        lblFecha.setBorder(null);
        lblFecha.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFechaMouseExited(evt);
            }
        });
        lblFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFechaActionPerformed(evt);
            }
        });
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 450, 40));

        lblNombre.setBackground(new java.awt.Color(22, 27, 34));
        lblNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Ingrese su nombre de usuario");
        lblNombre.setBorder(null);
        lblNombre.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNombreMouseExited(evt);
            }
        });
        lblNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNombreActionPerformed(evt);
            }
        });
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 740, 40));

        lblElegir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblElegir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElegirMouseClicked(evt);
            }
        });
        jPanel1.add(lblElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 50, 50));

        pnlSelector.setBackground(new java.awt.Color(13, 17, 23));

        optPrimeraHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optPrimeraHoraMouseClicked(evt);
            }
        });

        optSegundaHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optSegundaHoraMouseClicked(evt);
            }
        });

        optTerceraH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optTerceraHMouseClicked(evt);
            }
        });

        optCuartaH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optCuartaHMouseClicked(evt);
            }
        });

        optQuintaH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optQuintaHMouseClicked(evt);
            }
        });

        optDoceH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optDoceHMouseClicked(evt);
            }
        });

        optSextaH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optSextaHMouseClicked(evt);
            }
        });

        optAllDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optAllDayMouseClicked(evt);
            }
        });

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Seleccionar/ElegirClick.png"))); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bgMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectorLayout = new javax.swing.GroupLayout(pnlSelector);
        pnlSelector.setLayout(pnlSelectorLayout);
        pnlSelectorLayout.setHorizontalGroup(
            pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                .addComponent(optPrimeraHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSelectorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optSegundaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optTerceraH, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optCuartaH, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optQuintaH, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optDoceH, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optSextaH, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addComponent(optAllDay, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlSelectorLayout.setVerticalGroup(
            pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(optPrimeraHora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSelectorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSelectorLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(optSegundaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addContainerGap(148, Short.MAX_VALUE)
                    .addComponent(optTerceraH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addComponent(optCuartaH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(199, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addContainerGap(231, Short.MAX_VALUE)
                    .addComponent(optQuintaH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(optDoceH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addContainerGap(271, Short.MAX_VALUE)
                    .addComponent(optSextaH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
            .addGroup(pnlSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectorLayout.createSequentialGroup()
                    .addContainerGap(352, Short.MAX_VALUE)
                    .addComponent(optAllDay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 760, 430));

        lblElegido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblElegido.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblElegido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 690, 50));

        labelHorasC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1x/CantidadDeHoras.png"))); // NOI18N
        jPanel1.add(labelHorasC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 760, 70));

        jCheckBox2.setBackground(new java.awt.Color(13, 17, 23));
        jCheckBox2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Entrenador");
        jCheckBox2.setBorder(null);
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 750, 140, 30));

        jCheckBox1.setBackground(new java.awt.Color(13, 17, 23));
        jCheckBox1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Entrenador");
        jCheckBox1.setBorder(null);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 140, 30));

        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 980, 330, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ConfirmarReserva.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void lblNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseClicked
        lblNombre.setText("");
        lblNombre.setForeground(Color.decode("#f3e8ee"));
    }//GEN-LAST:event_lblNombreMouseClicked

    private void lblNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreMouseExited

    private void lblNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreActionPerformed

    private void lblFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMouseClicked
        lblFecha.setText("");
        lblNombre.setForeground(Color.decode("#f3e8ee"));

    }//GEN-LAST:event_lblFechaMouseClicked

    private void lblFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaMouseExited

    private void lblFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaActionPerformed

    private void lblHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoraMouseClicked
        lblHora.setText("");
    }//GEN-LAST:event_lblHoraMouseClicked

    private void lblHoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHoraMouseExited

    private void lblHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHoraActionPerformed

    private void lblMinutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinutoMouseClicked
        lblMinuto.setText("");
        int m = 0;

        try {
            m = Integer.parseInt(lblMinuto.getText());
        } catch (Exception e) {
            System.out.println("el dato tiene que ser un numero");
        }
        if (m < 30) {
            m = 0;
        } else if (m >= 30) {
            m = 30;
        }
    }//GEN-LAST:event_lblMinutoMouseClicked

    private void lblMinutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinutoMouseExited
        lblMinuto.setText(Integer.toString(Validaciones.RedondearMinutos(lblMinuto.getText())));
    }//GEN-LAST:event_lblMinutoMouseExited

    private void lblMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMinutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMinutoActionPerformed

    private void lblElegirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElegirMouseClicked
        if (c == 0) {
            c = 1;
            pnlSelector.setVisible(true);
            Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\ElegirClick.png");
            bg.setIcon(i);
        } else {
            pnlSelector.setVisible(false);
            c = 0;
        }

        lblElegido.setText(Validaciones.Elegir(Horas));

    }//GEN-LAST:event_lblElegirMouseClicked

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        ConfirmarReservaFrame v = new ConfirmarReservaFrame();
        v.setVisible(true);
        int min = Validaciones.RedondearMinutos(lblMinuto.getText());
        // 
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void optAllDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optAllDayMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\24 horas.png");
        bg.setIcon(i);
        Horas = 24;
    }//GEN-LAST:event_optAllDayMouseClicked

    private void optSextaHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optSextaHMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\6 horas.png");
        bg.setIcon(i);
        Horas = 6;
    }//GEN-LAST:event_optSextaHMouseClicked

    private void optDoceHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optDoceHMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\12 horas.png");
        bg.setIcon(i);
        Horas = 12;
    }//GEN-LAST:event_optDoceHMouseClicked

    private void optQuintaHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optQuintaHMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\5 horas.png");
        Horas = 5;
        bg.setIcon(i);
    }//GEN-LAST:event_optQuintaHMouseClicked

    private void optCuartaHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optCuartaHMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\4 horas.png");
        Horas = 4;
        bg.setIcon(i);
    }//GEN-LAST:event_optCuartaHMouseClicked

    private void optTerceraHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optTerceraHMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\3 horas.png");
        bg.setIcon(i);
        Horas = 3;
    }//GEN-LAST:event_optTerceraHMouseClicked

    private void optSegundaHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optSegundaHoraMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\2 horas.png");
        Horas = 2;
        bg.setIcon(i);
    }//GEN-LAST:event_optSegundaHoraMouseClicked

    private void optPrimeraHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optPrimeraHoraMouseClicked
        Icon i = new ImageIcon("C:\\Users\\Sebas\\Documents\\GitHub\\Parcial3Poo\\Coliseum\\src\\img\\Seleccionar\\1hora.png");
        bg.setIcon(i);
        Horas = 1;
    }//GEN-LAST:event_optPrimeraHoraMouseClicked

    private void bgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bgMouseExited

    private void SetImageLabel() {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarReservaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarReservaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarReservaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarReservaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarReservaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelHorasC;
    private javax.swing.JLabel lblElegido;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JTextField lblFecha;
    private javax.swing.JTextField lblHora;
    private javax.swing.JTextField lblMinuto;
    private javax.swing.JTextField lblNombre;
    private javax.swing.JLabel optAllDay;
    private javax.swing.JLabel optCuartaH;
    private javax.swing.JLabel optDoceH;
    private javax.swing.JLabel optPrimeraHora;
    private javax.swing.JLabel optQuintaH;
    private javax.swing.JLabel optSegundaHora;
    private javax.swing.JLabel optSextaH;
    private javax.swing.JLabel optTerceraH;
    private javax.swing.JPanel pnlSelector;
    // End of variables declaration//GEN-END:variables
}
