package Vista;

import Controlador.GestorClientes;
import Modelo.Cliente;
import Modelo.ListaClientes;

/**
 *
 * @author Sebas
 */
public class LoginFrame extends javax.swing.JFrame {

    ListaClientes lista_cliente = new ListaClientes();
    GestorClientes gc = GestorClientes.getInstance(lista_cliente, this);

    public LoginFrame() {
        initComponents();

        ocultarAvisos();
    }

    /**
     * Creates new form LoginFrame
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        lblRegistrarUser = new javax.swing.JTextField();
        lblRegistrarContraseña = new javax.swing.JPasswordField();
        lblLoginContraseña = new javax.swing.JPasswordField();
        lblLoginUser = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JLabel();
        lblAvisoClaveL = new javax.swing.JLabel();
        lblAvisoUsuarioR = new javax.swing.JLabel();
        lblAvisoUsuarioL = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, 50, 60));

        lblRegistrarUser.setBackground(new java.awt.Color(22, 27, 34));
        lblRegistrarUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblRegistrarUser.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistrarUser.setText("Ingrese su nombre de usuario");
        lblRegistrarUser.setBorder(null);
        lblRegistrarUser.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblRegistrarUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblRegistrarUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblRegistrarUserFocusLost(evt);
            }
        });
        jPanel1.add(lblRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 730, 50));

        lblRegistrarContraseña.setBackground(new java.awt.Color(22, 27, 34));
        lblRegistrarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistrarContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistrarContraseña.setText("              ");
        lblRegistrarContraseña.setBorder(null);
        lblRegistrarContraseña.setDoubleBuffered(true);
        lblRegistrarContraseña.setEchoChar('\u00d7');
        lblRegistrarContraseña.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblRegistrarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblRegistrarContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblRegistrarContraseñaFocusLost(evt);
            }
        });
        jPanel1.add(lblRegistrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 730, 50));

        lblLoginContraseña.setBackground(new java.awt.Color(19, 24, 30));
        lblLoginContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLoginContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lblLoginContraseña.setText("              ");
        lblLoginContraseña.setBorder(null);
        lblLoginContraseña.setEchoChar('\u00d7');
        lblLoginContraseña.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblLoginContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblLoginContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblLoginContraseñaFocusLost(evt);
            }
        });
        jPanel1.add(lblLoginContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 730, 50));

        lblLoginUser.setBackground(new java.awt.Color(19, 24, 30));
        lblLoginUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoginUser.setForeground(new java.awt.Color(204, 204, 204));
        lblLoginUser.setText("Ingrese su nombre de usuario");
        lblLoginUser.setBorder(null);
        lblLoginUser.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblLoginUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblLoginUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblLoginUserFocusLost(evt);
            }
        });
        jPanel1.add(lblLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 730, 50));

        BtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnRegistrarMouseReleased(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 770, 320, 50));

        BtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnLoginMouseReleased(evt);
            }
        });
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 770, 330, 50));

        lblAvisoClaveL.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoClaveL.setText("Contraseña incorrecta");
        jPanel1.add(lblAvisoClaveL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 250, -1));

        lblAvisoUsuarioR.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoUsuarioR.setText("El usuario ya está registrado");
        lblAvisoUsuarioR.setToolTipText("");
        jPanel1.add(lblAvisoUsuarioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 250, -1));

        lblAvisoUsuarioL.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoUsuarioL.setText("Usuario no registrado");
        jPanel1.add(lblAvisoUsuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 250, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRegistrarContraseñaFocusGained
        // TODO add your handling code here:
        if (lblRegistrarContraseña.getText().isBlank()) {
            lblRegistrarContraseña.setText("");
        }
    }//GEN-LAST:event_lblRegistrarContraseñaFocusGained

    private void lblRegistrarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRegistrarContraseñaFocusLost
        // TODO add your handling code here:
        if (lblRegistrarContraseña.getText().isBlank()) {
            lblRegistrarContraseña.setText("              ");
        }
    }//GEN-LAST:event_lblRegistrarContraseñaFocusLost

    private void lblRegistrarUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRegistrarUserFocusGained
        // TODO add your handling code here:
        if (lblRegistrarUser.getText().equalsIgnoreCase("Ingrese su nombre de usuario")) {
            lblRegistrarUser.setText("");
        }
    }//GEN-LAST:event_lblRegistrarUserFocusGained

    private void lblRegistrarUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRegistrarUserFocusLost
        // TODO add your handling code here:
        if (lblRegistrarUser.getText().isBlank()) {
            lblRegistrarUser.setText("Ingrese su nombre de usuario");
        }
    }//GEN-LAST:event_lblRegistrarUserFocusLost

    private void lblLoginUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoginUserFocusGained
        // TODO add your handling code here:
        if (lblLoginUser.getText().equalsIgnoreCase("Ingrese su nombre de usuario")) {
            lblLoginUser.setText("");
        }
    }//GEN-LAST:event_lblLoginUserFocusGained

    private void lblLoginUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoginUserFocusLost
        // TODO add your handling code here:
        if (lblLoginUser.getText().isBlank()) {
            lblLoginUser.setText("Ingrese su nombre de usuario");
        }
    }//GEN-LAST:event_lblLoginUserFocusLost

    private void lblLoginContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoginContraseñaFocusGained
        // TODO add your handling code here:
        if (lblLoginContraseña.getText().isBlank()) {
            lblLoginContraseña.setText("");
        }
    }//GEN-LAST:event_lblLoginContraseñaFocusGained

    private void lblLoginContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblLoginContraseñaFocusLost
        // TODO add your handling code here:
        if (lblLoginContraseña.getText().isBlank()) {
            lblLoginContraseña.setText("              ");
        }
    }//GEN-LAST:event_lblLoginContraseñaFocusLost

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseReleased

    private void BtnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseReleased
        // TODO add your handling code here:
        if (!lblLoginUser.getText().isBlank()
                && !lblLoginContraseña.getText().isBlank()) {
            if (gc.loginCliente()) {
                InicioFrame inicio = new InicioFrame();
                inicio.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_BtnLoginMouseReleased

    private void BtnRegistrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarMouseReleased
        // TODO add your handling code here:
        String usuario = lblRegistrarUser.getText();
        String contraseña = lblRegistrarContraseña.getText();

        if (!usuario.isBlank() && !usuario.contains(" ")
                && !contraseña.isBlank() && !contraseña.contains(" ")) {
            if (gc.registrarCliente()) {
                lblRegistrarUser.setText("Ingrese su nombre de usuario");
                lblRegistrarContraseña.setText("              ");
            }
        }
    }//GEN-LAST:event_BtnRegistrarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    public Cliente registrarCliente() {
        Cliente cliente = new Cliente();
        cliente.setUsuario(lblRegistrarUser.getText());
        cliente.setContraseña(lblRegistrarContraseña.getText());
        return cliente;
    }

    public Cliente ingresoCliente() {
        Cliente cliente = new Cliente();
        cliente.setUsuario(lblLoginUser.getText());
        cliente.setContraseña(lblLoginContraseña.getText());
        return cliente;
    }

    public void mostrarRegistrado() {
        lblAvisoUsuarioR.setVisible(true);
    }

    public void mostrarNoRegistrado() {
        lblAvisoUsuarioL.setVisible(true);
    }

    public void mostrarContraseñaIncorrecta() {
        lblAvisoClaveL.setVisible(true);
    }

    public void ocultarAvisos() {
        lblAvisoClaveL.setVisible(false);
        lblAvisoUsuarioL.setVisible(false);
        lblAvisoUsuarioR.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnLogin;
    private javax.swing.JLabel BtnRegistrar;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvisoClaveL;
    private javax.swing.JLabel lblAvisoUsuarioL;
    private javax.swing.JLabel lblAvisoUsuarioR;
    private javax.swing.JPasswordField lblLoginContraseña;
    private javax.swing.JTextField lblLoginUser;
    private javax.swing.JPasswordField lblRegistrarContraseña;
    private javax.swing.JTextField lblRegistrarUser;
    // End of variables declaration//GEN-END:variables
}
