package Vista;

import Controlador.GestorClientes;
import Modelo.Cliente;
import Modelo.ListaClientes;
import java.awt.Color;

/**
 *
 * @author Sebas
 */
public class LoginFrame extends javax.swing.JFrame {

    ListaClientes lista_cliente = new ListaClientes();
    GestorClientes gc = GestorClientes.getInstance(lista_cliente, this);

    public LoginFrame() {
        Cliente admin = new Cliente("admin", "Pr0gr4m4c10n", null, -1);
        lista_cliente.agregarCliente(admin);
        initComponents();
    }

    /**
     * Creates new form LoginFrame
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        lblRegistrarContraseña = new javax.swing.JTextField();
        lblRegistrarUser = new javax.swing.JTextField();
        lblLoginContraseña = new javax.swing.JTextField();
        lblLoginUser = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, 50, 60));

        lblRegistrarContraseña.setBackground(new java.awt.Color(22, 27, 34));
        lblRegistrarContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblRegistrarContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistrarContraseña.setText("Ingrese su contraseña");
        lblRegistrarContraseña.setBorder(null);
        lblRegistrarContraseña.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblRegistrarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 730, 50));

        lblRegistrarUser.setBackground(new java.awt.Color(22, 27, 34));
        lblRegistrarUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblRegistrarUser.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistrarUser.setText("Ingrese su nombre de usuario");
        lblRegistrarUser.setBorder(null);
        lblRegistrarUser.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblRegistrarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarUserMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 730, 50));

        lblLoginContraseña.setBackground(new java.awt.Color(19, 24, 30));
        lblLoginContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoginContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lblLoginContraseña.setText("Ingrese su contraseña");
        lblLoginContraseña.setBorder(null);
        lblLoginContraseña.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblLoginContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(lblLoginContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 730, 50));

        lblLoginUser.setBackground(new java.awt.Color(19, 24, 30));
        lblLoginUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoginUser.setForeground(new java.awt.Color(204, 204, 204));
        lblLoginUser.setText("Ingrese su nombre de usuario");
        lblLoginUser.setBorder(null);
        lblLoginUser.setSelectionColor(new java.awt.Color(0, 240, 181));
        lblLoginUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginUserMouseExited(evt);
            }
        });
        lblLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLoginUserActionPerformed(evt);
            }
        });
        jPanel1.add(lblLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 730, 50));

        BtnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 770, 320, 50));

        BtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 770, 330, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
        if (!lblLoginUser.getText().equals(null) 
                && !lblLoginContraseña.getText().equals(null)) {
            if (gc.loginCliente()) {
                InicioFrame inicio = new InicioFrame();
                inicio.setVisible(true);
            }
        }
    }//GEN-LAST:event_BtnLoginMouseClicked

    private void lblLoginUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginUserMouseClicked
        lblLoginUser.setText("");
        lblLoginUser.setForeground(Color.decode("#f3e8ee"));
    }//GEN-LAST:event_lblLoginUserMouseClicked

    private void lblLoginContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginContraseñaMouseClicked
        lblLoginContraseña.setText("");
        lblLoginContraseña.setForeground(Color.decode("#f3e8ee"));
    }//GEN-LAST:event_lblLoginContraseñaMouseClicked

    private void lblLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoginUserActionPerformed

    private void lblLoginUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginUserMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoginUserMouseExited

    private void lblRegistrarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarUserMouseClicked
        lblRegistrarUser.setText("");
        lblRegistrarUser.setForeground(Color.decode("#f3e8ee"));
    }//GEN-LAST:event_lblRegistrarUserMouseClicked

    private void lblRegistrarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarContraseñaMouseClicked
        lblRegistrarContraseña.setText("");
        lblRegistrarContraseña.setForeground(Color.decode("#f3e8ee"));
    }//GEN-LAST:event_lblRegistrarContraseñaMouseClicked

    private void BtnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarMouseClicked
        //  Registrar
        if (!lblRegistrarUser.getText().equals(null)
                && !lblRegistrarContraseña.getText().equals(null)) {
            if (gc.registrarCliente()) {
                lblRegistrarUser.setText("");
                lblRegistrarContraseña.setText("");
            } else {
                
            }
        }
    }//GEN-LAST:event_BtnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    public Cliente registrarCliente() {
        Cliente cliente = new Cliente(lblRegistrarUser.getText(),
                lblRegistrarContraseña.getText(), "", 0);
        return cliente;
    }

    public Cliente ingresoCliente() {
        Cliente cliente = new Cliente();
        System.out.println(lblLoginContraseña.getText());
        cliente.setUsuario(lblLoginUser.getText());
        cliente.setContraseña(lblLoginContraseña.getText());
        return cliente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnLogin;
    private javax.swing.JLabel BtnRegistrar;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblLoginContraseña;
    private javax.swing.JTextField lblLoginUser;
    private javax.swing.JTextField lblRegistrarContraseña;
    private javax.swing.JTextField lblRegistrarUser;
    // End of variables declaration//GEN-END:variables
}
